run:
	clear
	python3 hexercice.py client 192.168.47.162 Alice tablier 7

server:
	clear
	python3 hexercice.py server host

client:
	clear
	python3 hexercice.py client 127.0.0.1 client

help:
	clear
	python3 hexercice.py
