run:
	clear
	python3 hexercice.py client 192.168.47.162 Alice tablier 3

server:
	clear
	python3 hexercice.py server host tablier 6

serverP:
	clear
	python3 hexercice.py Bob pileouface tablier 5

client:
	clear
	python3 hexercice.py client 127.0.0.1 client tablier 6

clientP:
	clear
	python3 hexercice.py 127.0.0.1 Alice pileouface

help:
	clear
	python3 hexercice.py
